# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
arr_10 = np.ones(10)
arr_10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
arr_5 = np.ones(10)*5
arr_5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.array([[[0,1,2], [3,4,5], [6,7,8]]])

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Create a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
no = np.random.randint(0,1)
no

0

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.randn(5,5)

array([[ 0.46768807,  2.41691395, -0.94500545,  0.51370831,  0.28551669],
       [-1.86400765,  0.87877165, -0.48356443,  1.32139786, -1.09158768],
       [-0.02176951, -0.97515487, -1.8672044 ,  1.16828202, -1.49948807],
       [-0.02844216,  0.69386831, -0.49090919, -0.95250174,  0.32046944],
       [-0.638792  , -0.6072427 , -0.49482499,  2.12634095,  0.01133407]])

#### Create the following matrix:

In [35]:
arr = np.random.rand(10,10)
arr.reshape(10,10)


array([[0.28594479, 0.12122757, 0.07257614, 0.00325889, 0.5720519 ,
        0.40398866, 0.63205519, 0.28916144, 0.44866653, 0.86621001],
       [0.43112552, 0.09480911, 0.11410001, 0.35459556, 0.3150182 ,
        0.10642134, 0.47224406, 0.59240175, 0.28260567, 0.63162657],
       [0.26610581, 0.80226883, 0.42651447, 0.85008085, 0.94213547,
        0.49417554, 0.46027095, 0.84065914, 0.17412248, 0.70657162],
       [0.10925561, 0.53636485, 0.53298422, 0.13799992, 0.49427694,
        0.86719956, 0.58619851, 0.05320123, 0.05011435, 0.49381923],
       [0.81795884, 0.13349151, 0.18812422, 0.17782905, 0.8043423 ,
        0.64475047, 0.90327939, 0.81808549, 0.5104895 , 0.73421336],
       [0.52718681, 0.82277021, 0.23384515, 0.63915218, 0.23744702,
        0.68954445, 0.74413167, 0.79124823, 0.09867395, 0.15792718],
       [0.94015216, 0.26573283, 0.61975596, 0.1533631 , 0.17970211,
        0.45548718, 0.43768854, 0.12638215, 0.72297771, 0.10515199],
       [0.72260338, 0.60660335, 0.1550378

In [37]:
arr.reshape(10,10)

array([[0.28594479, 0.12122757, 0.07257614, 0.00325889, 0.5720519 ,
        0.40398866, 0.63205519, 0.28916144, 0.44866653, 0.86621001],
       [0.43112552, 0.09480911, 0.11410001, 0.35459556, 0.3150182 ,
        0.10642134, 0.47224406, 0.59240175, 0.28260567, 0.63162657],
       [0.26610581, 0.80226883, 0.42651447, 0.85008085, 0.94213547,
        0.49417554, 0.46027095, 0.84065914, 0.17412248, 0.70657162],
       [0.10925561, 0.53636485, 0.53298422, 0.13799992, 0.49427694,
        0.86719956, 0.58619851, 0.05320123, 0.05011435, 0.49381923],
       [0.81795884, 0.13349151, 0.18812422, 0.17782905, 0.8043423 ,
        0.64475047, 0.90327939, 0.81808549, 0.5104895 , 0.73421336],
       [0.52718681, 0.82277021, 0.23384515, 0.63915218, 0.23744702,
        0.68954445, 0.74413167, 0.79124823, 0.09867395, 0.15792718],
       [0.94015216, 0.26573283, 0.61975596, 0.1533631 , 0.17970211,
        0.45548718, 0.43768854, 0.12638215, 0.72297771, 0.10515199],
       [0.72260338, 0.60660335, 0.1550378

#### Create an array of 20 linearly spaced points between 0 and 1:

In [38]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [40]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [47]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [48]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [50]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!