Numpy Array Basics

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.array(arr)

array([0, 1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.ones(3,4)

TypeError: data type not understood

In [13]:
np.zeroes((3, 4))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [14]:
 np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [18]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [19]:
np.eyes(4)

AttributeError: module 'numpy' has no attribute 'eyes'

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.81249712, 0.07900632, 0.81074047, 0.43178335, 0.42523614])

In [22]:
np.random.rand(5,5)

array([[0.73844267, 0.55361403, 0.14915042, 0.61739872, 0.66160421],
       [0.73253063, 0.65815571, 0.74702391, 0.40971645, 0.71587618],
       [0.86876542, 0.74751573, 0.94474397, 0.76379285, 0.53359204],
       [0.72264499, 0.83733048, 0.64671836, 0.00404727, 0.83053254],
       [0.75941005, 0.99869061, 0.34856919, 0.76522588, 0.73143645]])

In [23]:
np.random.randn(2)

array([-0.82532068, -0.43492787])

In [24]:
np.random.randn(4, 4)

array([[ 0.35531383,  0.01289629, -0.65182422,  0.8445677 ],
       [ 0.16390499, -0.7322521 ,  0.43606894,  0.08779059],
       [ 0.70793157, -0.03544077, -0.74683485, -2.34959056],
       [-1.15347381,  0.14194332, -0.54415039,  0.49039394]])

In [25]:
np.random.randint(1, 100)

25

In [26]:
np.random.randint(1, 100, 10)

array([20, 38, 82, 49,  6, 21, 54, 98, 84, 15])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0, 50, 10)

In [30]:
ranarr

array([39, 48, 40, 47, 23, 31,  7, 45, 46, 30])

In [31]:
arr.reshape(4, 3)

ValueError: cannot reshape array of size 25 into shape (4,3)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr = np.arange(0, 24).reshape(6, 4)

In [34]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr.reshape(12, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [36]:
arr.reshape(2, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
ranarr.max()

48

In [38]:
ranarr.min()

7

In [39]:
ranarr.argmax()

1

In [40]:
ranarr.argmin()

6

In [41]:
arr.argmax()

23

In [42]:
arr.argmin()

0

In [43]:
arr.shape

(6, 4)

In [44]:
type(arr)

numpy.ndarray

In [45]:
arr.dtype

dtype('int32')

In [46]:
from numpy.random import randint
randint(2,3)

2

In [47]:
randint(3,4)

3

In [48]:
randint(100, 100000000000000000000000000000000)

ValueError: high is out of bounds for int32

In [49]:
randint(1, 10000000)

9068436

In [51]:
arr = np.arange(0, 11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[4]

4

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[0:5] = 100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [64]:
slice_of_arr[:] = 99

In [65]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy = arr.copy()

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy[:] = 100

In [71]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [74]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr_2d[0]

array([1, 2, 3])

In [76]:
arr_2d[0][1]

2

In [77]:
arr_3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [78]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
narr = np.array([[[[1,2,3], [4,5,6]]]])

In [87]:
narr[0]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [88]:
narr[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [89]:
arr_2d[2][1]

8

In [90]:
arr_2d[2,1]

8

In [91]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [93]:
arr_2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [94]:
arr > 3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [95]:
bool_arr = arr > 3

In [96]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [97]:
arr[arr>3]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [98]:
arr[arr < 3]

array([], dtype=int32)

In [99]:
arr[arr < 10]

array([6, 7, 8, 9])

In [100]:
arr = np.arange(0, 11)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [109]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [111]:
np.max(arr)

10

In [112]:
arr.max()

10

In [113]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])